require 'open3'
require 'pathname'
require 'fileutils'

$parentDir = File.dirname(__FILE__)

$androidHome = ENV['ANDROID_HOME']
raise 'Please set the ANDROID_HOME environment variable'.red.bold if $androidHome.nil?
$adbPath = "#{$androidHome}/platform-tools/adb"
$emulatorPath = "#{$androidHome}/tools/emulator"

$iosPluginSource = ["SwrveSDKCommon", "SwrveConversationSDK", "SwrveSDK"]

class String
	def green;          "\033[32m#{self}\033[0m" end
	def bg_red;         "\033[41m#{self}\033[0m" end
	def bold;           "\033[1m#{self}\033[22m" end
end

def announce(title)
	puts "[####] #{title}".green.bold
end

def exec(title, cmd)
	announce(title) unless title.nil?
	sh cmd do |ok, res|
 		raise "[####] #{title} failed with exit code #{res.exitstatus}".bg_red.bold unless ok || title.nil?
 		raise "[####] Last command failed with exit code #{res.exitstatus}".bg_red.bold unless ok
 	end
end

def error(title)
	raise "[####] #{title}".bg_red.bold
end

def relative(path)
	$parentDir + "/" + path
end

def execInDir(title, dir, cmd)
	exec(title, %Q{(cd #{dir}/; #{cmd})})
end

def killEmulator
	# Test if there is an emulator on this port
	%x{ #{$adbPath} -s emulator-5556 emu kill 2>/dev/null }
end

def killallXcode
  `killall Xcode; killall xcodebuild; killall Simulator;`
end

def waitForBoot(port)
	# If an emulator is not connected to within this time, we give up
	emulatorBootTimeout = 5*60
	# ADB restart every so often. It drops occasionally during emulator booting
	adbRestartDelay = 70
	# Need to provide general timeout
	nowTs = Time.now
	endTs = nowTs + emulatorBootTimeout
	# ADB restart timeout
	adbRestartTs = nowTs + adbRestartDelay

	signal1 = nil
	signal2 = nil
	signal3 = 0

	while signal1 != '1' && signal2 != 'stopped' && signal3.to_i <= 0 do
		# This one doesn't work on 2.1
		#`getprop sys.boot_completed`

		# This one typically finishes a bit too early
		signal1 = %x{ #{$adbPath} -s emulator-#{port} shell getprop dev.bootcomplete 2>/dev/null }

		# Wait for the boot animation to complete
		signal2 = %x{ #{$adbPath} -s emulator-#{port} shell getprop init.svc.bootanim 2>/dev/null }

		# Wait on the package manager
		# Warnings in 4.4.2 mean package isn't in the first line
		# Use grep
		signal3 = %x{ #{$adbPath} -s emulator-#{port} shell pm path android 2>/dev/null| grep package | wc -l }

		# Biggest problem is that adb needs reset sometimes
		# and we have no direct way of knowing when.
		# It could be the reason we are waiting.
		nowTs = Time.now
		if nowTs > adbRestartTs then
			# Been N seconds since we last restarted ADB
			puts "Restarting ABD in case it has lost the emulator connection"
			%x{ #{$adbPath} kill-server && #{$adbPath} start-server }
			adbRestartTs = nowTs + adbRestartDelay
		end
		# Add dots for progress
		print "."
	end

	return true
end

def startEmulator(emulator, port)
	# Start backgrounded
	exec("Starting emulator #{emulator} on port #{port}", "#{$emulatorPath} -avd '#{emulator}' -port #{port} &")

	# Boot test
	puts "Waiting for emulator #{emulator} on port #{port} to start".green.bold
	if waitForBoot(port) then
		return true
	end

	error("Emulator #{emulator} on port #{port} failed to boot.")
end

task :default => :build

# https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html
def generate_file_entries(dir, rel_plugin_path)
	file_declarations = ""
	Dir.entries(dir).reject{ |entry| entry == "." || entry == ".." }.each do |entry|
		entry_path = File.join(dir, entry)
		if File.directory?(entry_path) && !entry.end_with?(".xcassets")
			gen = generate_file_entries(entry_path, rel_plugin_path)
			file_declarations += gen unless gen.empty?
		else
			# Add single file
			relative_path = Pathname.new(entry_path).relative_path_from(Pathname.new(rel_plugin_path))
			target_path = Pathname.new(relative_path).relative_path_from(Pathname.new("platforms/ios/SwrveSDK/"))
			tag_type = "source-file"
			if relative_path.to_s.end_with?('.storyboard') || relative_path.to_s.end_with?('.xcassets')
				# Add as a resource
				tag_type = "resource-file"
			elsif relative_path.to_s.end_with? '.h'
				# Add as a header
				tag_type = "header-file"
			end

			file_declarations += "    <#{tag_type} src=\"#{relative_path}\" target-dir=\"#{target_path}\"/>\n"
		end
	end

	file_declarations
end

desc "Update the iOS plugin file references to native code"
task :updatePluginXml do
	# Upadte plugin.xml to reference all iOS source files individually, as including a folder seems
	# to be broken
	file_declarations = ""
	rel_plugin_path = $parentDir + "/SwrvePlugin/"
	$iosPluginSource.each do |folder|
		pluginPath = $parentDir + "/SwrvePlugin/platforms/ios/SwrveSDK/#{folder}"
		gen = generate_file_entries(pluginPath, rel_plugin_path)
		file_declarations += gen unless gen.empty?
	end

	# Replace injection point with entries and update plugin.xml
	injection_point = "<PLEASE_USE_RAKE_updatePluginXml/>"
	plugin_xml_content = File.read($parentDir + "/SwrvePlugin/plugin.base.xml")
	plugin_xml_content.sub!(injection_point, file_declarations)
	File.write($parentDir + "/SwrvePlugin/plugin.xml", plugin_xml_content)
end

desc "Build the demo for iOS and Android"
task :build => [:syncDemoPluginSource] do
	execInDir('Preparing', relative('SwrvePhoneGapDemo'), 'phonegap prepare')
	execInDir('Building PhoneGap iOS Demo', relative('SwrvePhoneGapDemo'), 'phonegap compile ios')
	execInDir('Building PhoneGap Android Demo', relative('SwrvePhoneGapDemo'), 'phonegap compile android')
end

desc "Sync the Demo's plugin source workaround"
task :syncDemoPluginSource do
	# Unfortunately with the modifications done to the Demo reinstalling the plugin won't work (known bug in cordova/phonegap).
	PLUGIN = "SwrvePlugin"
	DEMO = "SwrvePhoneGapDemo"
	DEMOIOS = "SwrvePhoneGapDemo/platforms/ios"
	DEMOANDROID = "SwrvePhoneGapDemo/platforms/android"

	# Global plugin
	FileUtils.copy_entry("#{PLUGIN}/", "#{DEMO}/plugins/com.swrve.SwrvePlugin/")

	# Android platform
	FileUtils.copy_entry("#{PLUGIN}/platforms/android/build.gradle", "#{DEMOANDROID}/com.swrve.SwrvePlugin/helloworld-build.gradle")
	FileUtils.copy_entry("#{PLUGIN}/platforms/android/src/com/swrve/SwrvePlugin.java", "#{DEMOANDROID}/src/com/swrve/SwrvePlugin.java")
	# Add JS plugin wrappings
	File.write("#{DEMOANDROID}/assets/www/plugins/com.swrve.SwrvePlugin/js/swrve-android.js", ("cordova.define(\"com.swrve.SwrvePlugin.SwrvePlugin\", function(require, exports, module) {" + File.read("#{PLUGIN}/js/swrve-android.js") + "});"))

	FileUtils.copy_entry("#{DEMOANDROID}/assets/www/plugins/com.swrve.SwrvePlugin/js/swrve-android.js", "#{DEMOANDROID}/platform_www/plugins/com.swrve.SwrvePlugin/js/swrve-android.js")

	# iOS platform
	# Copy main plugin
	FileUtils.copy_entry("#{PLUGIN}/platforms/ios/SwrvePlugin.h", "#{DEMOIOS}/SwrvePhoneGapDemo/Plugins/com.swrve.SwrvePlugin/SwrvePlugin.h")
	FileUtils.copy_entry("#{PLUGIN}/platforms/ios/SwrvePlugin.m", "#{DEMOIOS}/SwrvePhoneGapDemo/Plugins/com.swrve.SwrvePlugin/SwrvePlugin.m")

	# Copy native code
	except_extensions = [".xcassets", ".storyboard"]
	$iosPluginSource.each do |folder|
		copyWithWrappingFolder("#{PLUGIN}/platforms/ios/SwrveSDK/#{folder}/", "#{DEMOIOS}/SwrvePhoneGapDemo/Plugins/com.swrve.SwrvePlugin/#{folder}/", except_extensions)
	end

	# Copy resources
	FileUtils.copy_entry("#{PLUGIN}/platforms/ios/SwrveSDK/SwrveConversationSDK/Resources/SwrveAssets.xcassets", "#{DEMOIOS}/SwrvePhoneGapDemo/Resources/SwrveAssets.xcassets")
	FileUtils.copy_entry("#{PLUGIN}/platforms/ios/SwrveSDK/SwrveConversationSDK/Resources/SwrveConversation.storyboard", "#{DEMOIOS}/SwrvePhoneGapDemo/Resources/SwrveConversation.storyboard")

	# Add JS plugin wrappings
	File.write("#{DEMOIOS}/www/plugins/com.swrve.SwrvePlugin/js/swrve-ios.js", ("cordova.define(\"com.swrve.SwrvePlugin.SwrvePlugin\", function(require, exports, module) {" + File.read("#{PLUGIN}/js/swrve-ios.js") + "});"))

	FileUtils.copy_entry("#{DEMOIOS}/www/plugins/com.swrve.SwrvePlugin/js/swrve-ios.js", "#{DEMOIOS}/platform_www/plugins/com.swrve.SwrvePlugin/js/swrve-ios.js")
end

def copyWithWrappingFolder(orig, dest, except_extensions)
	Dir.entries(orig).each do |entry|
		if entry != '.' && entry != '..'
			orig_path = File.join(orig, entry)
			dest_path = File.join(dest, entry)

			unless except_extensions.any? { |extension| entry.end_with? extension }
				if File.directory? orig_path
					copyWithWrappingFolder(orig_path, dest_path, except_extensions)
				else
					# Create wrapping folder for it like Cordova does
					unless File.exists? dest_path
						FileUtils::mkdir_p(dest_path)
					end

					# Copy file inside the wrapper folder
					entry_wrapped_path = File.join(dest_path, entry)
					FileUtils.copy_entry(orig_path, entry_wrapped_path)
				end
			end
		end
	end
end

desc "Launch iOS simulator and tests"
task :testIOSInSimulator, [:simulator] do |t, args|
	killallXcode
	# Example: "OS=8.3,name='iPad Air'"
	simulator = args[:simulator]
	execInDir("Testing PhoneGap iOS wrapper on #{simulator}", relative('SwrvePhoneGapDemo/platforms/ios'), "xcodebuild clean test -scheme 'SwrvePhoneGapDemo' -destination #{simulator}")
	killallXcode
end

desc "Launch Android emulator and tests"
task :testAndroidInEmulator, [:emulator] do |t, args|
	# Example: "Nexus"
	emulator = args[:emulator]
	emulatorPort = 5556

	killEmulator

	startEmulator(emulator, emulatorPort)
	# Output logcat to packages folder for when we need it
	logcatThread = Thread.new {
		while true do
			%x{ #{$adbPath} logcat -d > #{$parentDir}/emu_#{emulator}.logcat }
			sleep(0.5)
		end
	}
	Rake::Task["testAndroidConnectedDevice"].execute
	sleep(5)
	logcatThread.exit

	killEmulator
end

desc "Launch tests on the connected Android device"
task :testAndroidConnectedDevice do
	execInDir("Testing PhoneGap Android wrapper", relative('SwrvePhoneGapDemo/platforms/android'), "./gradlew connectedCheck")
end

desc "Build and package the PhoneGap wrapper"
task :createPackage do
	fileName = "phonegap-wrapper-rc.zip"
	announce("Packaging PhoneGap wrapper #{fileName}")
	execInDir(nil, $parentDir, "rm -f #{fileName}")
	execInDir(nil, $parentDir, "git submodule init; git submodule sync; git submodule update --force;")
	# Add code
	execInDir(nil, $parentDir, "git ls-files | zip -@ #{fileName}")
	# Add swrve-ios-sdk code
	execInDir(nil, relative('SwrvePlugin/platforms/ios/SwrveSDK/'), "git clean -dfx && git reset --hard")
	execInDir(nil, $parentDir, "zip -r #{fileName} SwrvePlugin/platforms/ios/SwrveSDK/*")
end
